# Generated by Django 4.0.6 on 2022-07-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Sock Design', max_length=100)),
                ('CC1', models.CharField(default='white', max_length=100)),
                ('CC2', models.CharField(default='yellow', max_length=100)),
                ('CC3', models.CharField(default='red', max_length=100)),
                ('ankle_height', models.CharField(default='crew', max_length=100)),
                ('foot_length', models.CharField(default='9.5', max_length=100)),
                ('user_photo', models.TextField()),
            ],
        ),
    ]
