# Generated by Django 4.0.6 on 2022-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsock',
            name='user_photo',
            field=models.TextField(blank=True),
        ),
    ]
