# Generated by Django 4.0.6 on 2022-07-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0002_alter_basicsock_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsock',
            name='CC2',
            field=models.CharField(blank=True, default='yellow', max_length=100),
        ),
        migrations.AlterField(
            model_name='basicsock',
            name='CC3',
            field=models.CharField(blank=True, default='red', max_length=100),
        ),
    ]
