# Generated by Django 4.0.6 on 2022-07-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0006_alter_basicsock_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsock',
            name='user_photo',
            field=models.TextField(default='upload photo here'),
        ),
    ]
