# Generated by Django 4.0.6 on 2022-07-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0007_alter_basicsock_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicsock',
            old_name='CC1',
            new_name='toeColor',
        ),
        migrations.RemoveField(
            model_name='basicsock',
            name='CC2',
        ),
        migrations.RemoveField(
            model_name='basicsock',
            name='CC3',
        ),
        migrations.AddField(
            model_name='basicsock',
            name='ankleColor',
            field=models.CharField(blank=True, default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='basicsock',
            name='footColor',
            field=models.CharField(blank=True, default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='basicsock',
            name='heelColor',
            field=models.CharField(blank=True, default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='basicsock',
            name='ribColor',
            field=models.CharField(blank=True, default='white', max_length=100),
        ),
    ]
