# Generated by Django 4.0.6 on 2022-07-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socklab', '0008_rename_cc1_basicsock_toecolor_remove_basicsock_cc2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicsock',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basicsock',
            name='user_photo',
            field=models.TextField(blank=True),
        ),
    ]
