# Generated by Django 4.0.6 on 2022-07-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0009_basicsock_created_at_basicsock_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsock',
            name='owner',
        ),
    ]
