# Generated by Django 4.0.6 on 2022-07-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0011_remove_basicsock_ankle_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicsock',
            old_name='status',
            new_name='knitstatus',
        ),
    ]
