# Generated by Django 4.0.6 on 2022-07-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0012_rename_status_basicsock_knitstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicsock',
            old_name='knitstatus',
            new_name='knitStatus',
        ),
    ]
