# Generated by Django 4.0.6 on 2022-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0014_alter_basicsock_knitstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='Brand', max_length=400)),
                ('colorName', models.CharField(default='white', max_length=400)),
                ('colorCode', models.CharField(default='#fff', max_length=100)),
                ('yardage', models.CharField(blank=True, max_length=100)),
                ('grams', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
