# Generated by Django 4.0.6 on 2022-07-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0015_stash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stash',
            name='colorName',
            field=models.CharField(blank=True, default='white', max_length=400),
        ),
    ]
