# Generated by Django 4.0.6 on 2022-09-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socklab', '0016_alter_stash_colorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
